### ISSUE TITLE
ramlev validation challenge 

### ISSUE THREAD

**Issue by eswarantg** [cybertk/ramlev#20]
I am looking to use ramlev in my project

Have uploaded a working sample project in 
https://github.com/eswarantg/sampleRestIf_RAML

The goal here is to organize the Interface and schema files across folders.
using commandline : ramlev $1 -f $BASE_URL -d "$SCHEMA_DIR"

I get the following output
  /doctors
    ✓ GET response 200 
    ✓ GET response 204 
    ✓ POST request 
    ✓ POST response 209 

  /doctors/{doctorId}
    ✓ GET response 200 
    ✓ GET response 404 
    ✓ POST request 
    ✓ POST response 200 
    ✓ POST response 209 
    ✓ POST response 404 
    ✓ DELETE response 200 
    ✓ DELETE response 404 

  /patients
    ✓ GET response 200 
    ✓ GET response 204 

  /patients/{patientId}
    ✓ GET response 200 
    ✓ GET response 404 

  16 passing (16ms)

I expect the GET "/patients/{patientId}" to fail due to the wrong data
{
  "ID" : "ERR",
  "name" : "PQRS",
  "sex" : "Male",
  "diagnosis" : [
	  "Fracture in left leg"
	  ,"15 days rest"
  ]
}

ID is integer type.

I bet i am missing something here.

**Comment by robertlevy** [comment]
any luck on this?

**Comment by cybertk** [comment]
I saw there is no test for `GET "/patients/{patientId}" with wrong data`
