### ISSUE TITLE
Missing properties not caught?

### ISSUE THREAD

**Issue by bpytlik** [cybertk/ramlev#21]
Here's a raml file (adapted from the RAML 200 tutorial example):
```
#%RAML 0.8
---
title: Jukebox API


/songs:
  get:
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "type": "object",
                "$schema": "http://json-schema.org/draft-03/schema",
                "id": "http://jsonschema.net",
                "required": true,
                "properties": {
                  "songTitle": {
                    "type": "string",
                    "required": true
                  }
                }
              }
            example: |
              {
                "foo": "Get Lucky"
              }
```

And here's what happens when I test my example against the schema.
```
./dev_deps/node_modules/.bin/ramlev ./test.raml 


  /songs
    ✓ GET response 200 


  1 passing (11ms)
```

I would have expected the test to fail because:
1) the required property "songTitle" isn't in the example
2) there's an unexpected property named "foo" in the example

Any idea what I'm doing wrong?

**Comment by cybertk** [comment]
Could you try to use draft-4 version schema, as ramlev use [tv4][1] for underling jsonschema validation which supports draft 4 only.

[1]: https://github.com/geraintluff/tv4

**Comment by bpytlik** [comment]
Sorry, this works once I got the schema right. I didn't realize the RAML tutorial was using an old/bad example for the required property.

**Comment by cybertk** [comment]
I think we can add a warning prompt when jsonschema is not draft-4
