### ISSUE TITLE
release new ramlev version

### ISSUE THREAD

**Issue by arnelandwehr** [cybertk/ramlev#23]
Hi,

working together with @andrenpaes on the same project, where we would like to use ramlev. Actually we need a version that includes his latest accepted [PR](https://github.com/cybertk/ramlev/pull/22). 

Tried to reference this repo as snapshot in our package.json (i am not really an node/npm expert ;)) but due to the .npmignore file it doesn't include the sources.

Could you release a new version or give me a hint how i easily could reference a snapshot version?

Thx!

**Comment by cybertk** [comment]
You can use `npm i git://github.com/cybertk/ramlev.git#master`

**Comment by arnelandwehr** [comment]
still the same outcome for me:

```
ramlev:
- .npmignore 
- LICENSE
- README.md 
- bin 
- lib 
- node_modules 
- package.json
```

the issue is also mentioned here: https://github.com/npm/npm/issues/7262 and still open :(.

Proposed solutions include:
> 1. Publishing from a tarball would definitely work
> 2. Having separate 'stable' and 'next' release lines with dist-tags that follow the different dev branches is probably what I would recommend, to reduce your users' dependence on github-based installs , if you wanted to do that (that's the way I'd go)

**Comment by cybertk** [comment]
The dir structure is correct, could you try run `./node_modules/ramlev/bin/ramlev`

**Comment by arnelandwehr** [comment]
ah sry missed that the lib folder is there and already includes the latest sources. Works like a charm!

Thx for the help :)
